import { A } from '../theme'

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, color: A.text, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ fontSize: 13, color: A.textMuted, marginBottom: 32 }}>Last updated: February 27, 2026</p>

      <div style={{ fontSize: 14, color: A.textSoft, lineHeight: 1.8 }}>
        <Section title="1. Acceptance of Terms">
          By accessing or using Amplispark ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </Section>

        <Section title="2. Description of Service">
          Amplispark is an AI-powered content generation platform that analyzes your brand, creates social media content strategies, and generates captions and images using Google's Gemini API and Veo video generation. The Service is provided as a hackathon project and demonstration tool.
        </Section>

        <Section title="3. User Accounts">
          The Service uses anonymous authentication. No email, password, or personal information is required to use Amplispark. Your brand data is associated with an anonymous session identifier stored in your browser.
        </Section>

        <Section title="4. User Content">
          <p style={{ marginBottom: 12 }}>You retain ownership of all content you provide to the Service, including brand descriptions, uploaded images, and business information ("User Content").</p>
          <p style={{ marginBottom: 12 }}>By using the Service, you grant Amplispark a non-exclusive, temporary license to process your User Content solely for the purpose of generating content on your behalf.</p>
          <p>AI-generated content (captions, images, videos) created by the Service is provided for your use. You are responsible for reviewing all generated content before publishing it on any platform.</p>
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to use the Service to:
          <ul style={{ paddingLeft: 20, marginTop: 8 }}>
            <li>Generate content that is illegal, harmful, or violates third-party rights</li>
            <li>Misrepresent AI-generated content as human-created where disclosure is required</li>
            <li>Attempt to reverse-engineer or extract the underlying AI models</li>
            <li>Overload the Service with automated requests beyond normal use</li>
          </ul>
        </Section>

        <Section title="6. AI-Generated Content Disclaimer">
          Content generated by Amplispark is produced by artificial intelligence (Google Gemini) and may contain inaccuracies, biases, or content that does not perfectly align with your brand. You are solely responsible for reviewing, editing, and approving all content before publication. Amplispark does not guarantee the accuracy, quality, or suitability of any generated content.
        </Section>

        <Section title="7. Third-Party Services">
          Amplispark integrates with third-party services including Google Cloud, Notion, and Buffer. Your use of these integrations is subject to the respective third-party terms of service. Amplispark is not responsible for the availability or performance of third-party services.
        </Section>

        <Section title="8. Intellectual Property">
          The Amplispark name, logo, and platform design are the property of the Amplispark team. The underlying AI models (Gemini, Veo) are the property of Google. All other trademarks belong to their respective owners.
        </Section>

        <Section title="9. Limitation of Liability">
          The Service is provided "as is" without warranties of any kind. Amplispark is a hackathon project and is not intended for production use without additional review. To the maximum extent permitted by law, Amplispark shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.
        </Section>

        <Section title="10. Changes to Terms">
          We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.
        </Section>

        <Section title="11. Contact">
          For questions about these Terms, please reach out through the project's GitHub repository.
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontSize: 16, fontWeight: 600, color: A.text, marginBottom: 8 }}>{title}</h2>
      <div>{children}</div>
    </div>
  )
}
